#!/usr/bin/env python3
"""Run and time a project euler script from the given ID"""

import argparse
import importlib
import sys
import datetime as dt
import humanize

# Parse the ID from the command line via `argparse`
parser = argparse.ArgumentParser(description="Run a Project Euler project")
parser.add_argument('project', type=int, help='project ID to be executed')
args = parser.parse_args()


filename = 'problems.p{:0>3}'.format(args.project)

# This fixes `util` not being able to be imported
sys.path.append('problems')

module = importlib.import_module(filename)

# Show the title of the script, generated via `generate.py`
print(module.__doc__)

# Make sure we're only timing the solving of the problem
start_time = dt.datetime.now()
output = module.solve()
end_time = dt.datetime.now()

delta = end_time - start_time

print("\nDone!")
print("Time elapsed:", humanize.precisedelta(delta))
print("Result:", output)

